name: taqo_upload
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  taqo_common:
    path: ../taqo_common
  pal_event_server:
    path: ../pal_event_server

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
