package com.pacoapp.intellij;

public class PacoIntellijEventTypes {

  public enum EventType {
    DOCUMENT_SAVED, DOCUMENT_CHANGED, DOCUMENT_CREATED, DOCUMENT_DELETED,
    DOCUMENT_MOVED, DOCUMENT_COPIED, DOCUMENT_REFRESHED,
    DOCUMENT_OPENED, DOCUMENT_CLOSED, DOCUMENT_FOCUSED,
    COPY_ACTION, CUT_ACTION, PASTE_ACTION, UNDO_ACTION, REDO_ACTION,
    IDE_STARTED, IDE_STOPPED,
    LAUNCH,
    PROJECT_OPENED, IDE_ACTION, PROJECT_COMPILATION, PROJECT_SNAPSHOT, DIFF, PROJECT_CLOSED
  }
}
